version: "3"

services:
  postgres:
    image: "majid7221/postgres:${IMAGE_TAG}"
    restart: until-stopped
    stop_grace_period: 15m
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DATABASE}'
    ports:
      - 5432:5432
